#BSUB -J Fig4A[1-441]
#BSUB -W 15:00
#BSUB -o /rsrch8/home/biostatistics/zliu20/test/csmGmm_sim_R2/Fig4/errDir/Fig4A_log%I.out
#BSUB -e /rsrch8/home/biostatistics/zliu20/test/csmGmm_sim_R2/Fig4/errDir/Fig4A_%I.err
#BSUB -cwd /rsrch8/home/biostatistics/zliu20/test/csmGmm_sim_R2/
#BSUB -q medium
#BSUB -u ZLiu20@mdanderson.org
#BSUB -n 1
#BSUB -M 8
#BSUB -R rusage[mem=4]
# run 1-400
module load R/4.5.1
Rscript /rsrch8/home/biostatistics/zliu20/test/csmGmm_sim_R2/Fig4/Fig4A_sim.R $LSB_JOBINDEX 1 >/rsrch8/home/biostatistics/zliu20/test/csmGmm_sim_R2/Fig4/errDir/Fig4A_$LSB_JOBINDEX.out
