#BSUB -J Fig2B[1-400]
#BSUB -W 18:00
#BSUB -o /rsrch8/home/biostatistics/zliu20/test/csmGmm_sim_R2/Fig2/errDir/Fig2B_log%I.out
#BSUB -e /rsrch8/home/biostatistics/zliu20/test/csmGmm_sim_R2/Fig2/errDir/Fig2B_%I.err
#BSUB –cwd /rsrch8/home/biostatistics/zliu20/test/csmGmm_sim_R2/
#BSUB -q medium
#BSUB -u ZLiu20@mdanderson.org
#BSUB -n 4
#BSUB -M 32
#BSUB -R rusage[mem=4]

# run 1-400
module load R/4.5.1
Rscript /rsrch8/home/biostatistics/zliu20/test/csmGmm_sim_R2/Fig2/Fig2B_sim.R $LSB_JOBINDEX 1 >/rsrch8/home/biostatistics/zliu20/test/csmGmm_sim_R2/Fig2/errDir/Fig2B_$LSB_JOBINDEX.out
