#BSUB -J summarizeS2[1-1]
#BSUB -W 1:00
#BSUB -o /rsrch8/home/biostatistics/zliu20/test/csmGmm_sim_R2/Fig7/errDir/summarize_ukb_S2_log%I.out
#BSUB -e /rsrch8/home/biostatistics/zliu20/test/csmGmm_sim_R2/Fig7/errDir/summarize_ukb_S2_%I.err
#BSUB –cwd /rsrch8/home/biostatistics/zliu20/test/csmGmm_sim_R2/
#BSUB -q short
#BSUB -u ZLiu20@mdanderson.org
#BSUB -n 1
#BSUB -M 32
#BSUB -R rusage[mem=32]

# run 1-1
module load R/4.5.1
Rscript /rsrch8/home/biostatistics/zliu20/test/csmGmm_sim_R2/Fig7/summarize_ukb_analysis_R1.R $LSB_JOBINDEX 2 >/rsrch8/home/biostatistics/zliu20/test/csmGmm_sim_R2/Fig7/errDir/summarize_ukb_S2_$LSB_JOBINDEX.out
